name: First Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


  deploy:
    name: Deploy to Render
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Deploy via Render Deploy Hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"