name: First Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:

      # 1. GitHub repository ka code checkout karo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Python install karo
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # 3. Dependencies install karo
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Basic test
      - name: Run tests
        run: |
          python -m compileall .