name : First pipeline

on:
    push:
      branches:
        -main

jobs:
    build :
      name: build project
      runs-on: ubuntu-latest

      steps:
        - name : checkout code
          uses : actions/checkout@v4

        - name : install python
          uses : actions/setup-python@v5
          with : 
            python-version : "3.13"

        - name : install dependecies
          run : 
            pip -m install --upgrade pip 
            pip install -r requirements.txt

deploy: 
  name : Deploy to render
  needs : build
  runs-on: ubuntu-latest

  steps : 
    -name : Deploy via Render Deploy Hook
    run : 
      curl -X POST "${{ secretes.RENDER_DEPLOY_HOOK }}"